cat > cloudbuild.yaml << 'EOF'
steps:
  # 1) Build API Docker image from apps/api/Dockerfile
  - name: gcr.io/cloud-builders/docker
    id: build-api-image
    args:
      [
        "build",
        "-f",
        "apps/api/Dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/nexus-api:$COMMIT_SHA",
        ".",
      ]

  # 2) Push API image
  - name: gcr.io/cloud-builders/docker
    id: push-api-image
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/nexus-api:$COMMIT_SHA",
      ]

  # 3) Run Prisma migrate deploy inside the built image (in GCP)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: migrate-prod-db
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        echo "=== Fetching DATABASE_URL from Secret Manager ==="
        export DATABASE_URL="$(gcloud secrets versions access latest --secret=prod-database-url)"
        echo "=== Running prisma migrate deploy ==="
        docker run --rm \
          -e DATABASE_URL="$DATABASE_URL" \
          gcr.io/$PROJECT_ID/nexus-api:$COMMIT_SHA \
          npx prisma migrate deploy --schema=packages/database/prisma/schema.prisma

  # 4) Deploy the new image to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy-cloud-run
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "nexus-api",                # Cloud Run service name
        "--image",
        "gcr.io/$PROJECT_ID/nexus-api:$COMMIT_SHA",
        "--region",
        "us-central1",              # adjust if needed
        "--platform",
        "managed",
        "--set-env-vars",
        "DATABASE_URL=secret:prod-database-url,NODE_ENV=production",
      ]

images:
  - "gcr.io/$PROJECT_ID/nexus-api:$COMMIT_SHA"
EOF