# Cloud Run service definition for the Nexus API.
#
# ⚠️  THIS FILE IS A REFERENCE TEMPLATE ONLY.
#
# The actual production configuration is managed via `gcloud run services update`
# commands in the deployment workflow (.github/workflows/prod-api-deploy.yml).
# Environment variables (DATABASE_URL, REDIS_URL, etc.) are set directly on
# Cloud Run, NOT from this file.
#
# To view actual production config:
#   gcloud run services describe nexus-api --region=us-central1 --format=yaml
#
# To update an env var:
#   gcloud run services update nexus-api --region=us-central1 --update-env-vars="KEY=value"
#
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nexus-api
  namespace: nexus-enterprise-480610
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: us-docker.pkg.dev/nexus-enterprise-480610/nexus-api/nexus-api:latest
          env:
            # Actual values are set via gcloud CLI, not this file.
            # These are placeholders for documentation purposes.
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              value: "${DATABASE_URL}"  # Set via: gcloud run services update --update-env-vars
            - name: REDIS_URL
              value: "${REDIS_URL}"     # Redis VM: redis-prod (us-central1-a), port 6379, password auth
            - name: JWT_ACCESS_SECRET
              value: "${JWT_ACCESS_SECRET}"
            - name: JWT_REFRESH_SECRET
              value: "${JWT_REFRESH_SECRET}"
            - name: GCS_UPLOADS_BUCKET
              value: "${GCS_UPLOADS_BUCKET}"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 4
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health/deps
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 10
      timeoutSeconds: 300
