-- Add mid-level trade grouping to skills
ALTER TABLE "SkillDefinition" ADD COLUMN IF NOT EXISTS "tradeLabel" TEXT;

-- Deactivate previous starter catalog (kept for history)
UPDATE "SkillDefinition"
SET "active" = false
WHERE "categoryId" IN (
  'CAT_STRUCTURAL',
  'CAT_ROOFING',
  'CAT_FINISHES',
  'CAT_MANAGEMENT',
  'CAT_ESTIMATING'
);

UPDATE "SkillCategory"
SET "active" = false
WHERE "id" IN (
  'CAT_STRUCTURAL',
  'CAT_ROOFING',
  'CAT_FINISHES',
  'CAT_MANAGEMENT',
  'CAT_ESTIMATING'
);

-- Seed construction functional areas (categories)
INSERT INTO "SkillCategory" ("id", "code", "label", "sortOrder", "active") VALUES
  ('CAT_SITE_WORK', 'SITE_WORK', 'Site Work', 10, true),
  ('CAT_FOUNDATION', 'FOUNDATION', 'Foundation', 20, true),
  ('CAT_STRUCTURAL_FRAMING', 'STRUCTURAL_FRAMING', 'Structural / Framing', 30, true),
  ('CAT_ROOFING_NEW', 'ROOFING_NEW', 'Roofing', 40, true),
  ('CAT_EXTERIOR_ENVELOPE_FINISHES', 'EXTERIOR_ENVELOPE_FINISHES', 'Exterior Envelope / Finishes', 50, true),
  ('CAT_DOORS_WINDOWS', 'DOORS_WINDOWS', 'Doors and Windows', 60, true),
  ('CAT_MECHANICAL_HVAC', 'MECHANICAL_HVAC', 'Mechanical (HVAC)', 70, true),
  ('CAT_ELECTRICAL_NEW', 'ELECTRICAL_NEW', 'Electrical', 80, true),
  ('CAT_PLUMBING_NEW', 'PLUMBING_NEW', 'Plumbing', 90, true),
  ('CAT_INSULATION_MOISTURE', 'INSULATION_MOISTURE', 'Insulation and Moisture Protection', 100, true),
  ('CAT_DRYWALL_NEW', 'DRYWALL_NEW', 'Drywall', 110, true),
  ('CAT_INTERIORS_FINISHES', 'INTERIORS_FINISHES', 'Interiors / Finishes', 120, true),
  ('CAT_KITCHEN_BATH_CABINETRY', 'KITCHEN_BATH_CABINETRY', 'Kitchen, Bath, and Cabinetry', 130, true),
  ('CAT_SPECIALTIES_EQUIPMENT', 'SPECIALTIES_EQUIPMENT', 'Specialties and Equipment', 140, true),
  ('CAT_FIRE_PROTECTION', 'FIRE_PROTECTION', 'Fire Protection', 150, true),
  ('CAT_LANDSCAPING_EXTERIOR', 'LANDSCAPING_EXTERIOR', 'Landscaping and Exterior Improvements', 160, true)
ON CONFLICT ("code") DO UPDATE
SET
  "label" = EXCLUDED."label",
  "sortOrder" = EXCLUDED."sortOrder",
  "active" = true;

-- Seed construction sub-skill tasks (Functional Area -> Trade -> Sub-skill/Task)
-- NOTE: id values are stable strings; code is the unique key.
INSERT INTO "SkillDefinition" ("id", "categoryId", "code", "label", "tradeLabel", "description", "sortOrder", "active") VALUES
  -- Site Work / Surveyors
  ('SK_SITE_WORK_SURVEYORS_LAND_SURVEYING_TOTAL_STATIONS_GPS', 'CAT_SITE_WORK', 'SITE_WORK_SURVEYORS_LAND_SURVEYING_TOTAL_STATIONS_GPS', 'Land surveying (using total stations/GPS)', 'Surveyors', NULL, 10, true),
  ('SK_SITE_WORK_SURVEYORS_SITE_LAYOUT_STAKING', 'CAT_SITE_WORK', 'SITE_WORK_SURVEYORS_SITE_LAYOUT_STAKING', 'Site layout and staking', 'Surveyors', NULL, 20, true),

  -- Site Work / Excavators and Graders
  ('SK_SITE_WORK_EXCAVATORS_GRADERS_EARTH_MOVING_EXCAVATION', 'CAT_SITE_WORK', 'SITE_WORK_EXCAVATORS_GRADERS_EARTH_MOVING_EXCAVATION', 'Earth moving and excavation', 'Excavators and Graders', NULL, 10, true),
  ('SK_SITE_WORK_EXCAVATORS_GRADERS_SITE_CLEARING', 'CAT_SITE_WORK', 'SITE_WORK_EXCAVATORS_GRADERS_SITE_CLEARING', 'Site clearing (vegetation/debris removal)', 'Excavators and Graders', NULL, 20, true),
  ('SK_SITE_WORK_EXCAVATORS_GRADERS_GRADING_LEVELING', 'CAT_SITE_WORK', 'SITE_WORK_EXCAVATORS_GRADERS_GRADING_LEVELING', 'Grading and leveling', 'Excavators and Graders', NULL, 30, true),

  -- Site Work / Demolition Crews
  ('SK_SITE_WORK_DEMOLITION_CREWS_STRUCTURE_DEMOLITION', 'CAT_SITE_WORK', 'SITE_WORK_DEMOLITION_CREWS_STRUCTURE_DEMOLITION', 'Structure demolition (controlled teardown)', 'Demolition Crews', NULL, 10, true),
  ('SK_SITE_WORK_DEMOLITION_CREWS_DEBRIS_REMOVAL_RECYCLING', 'CAT_SITE_WORK', 'SITE_WORK_DEMOLITION_CREWS_DEBRIS_REMOVAL_RECYCLING', 'Debris removal and recycling', 'Demolition Crews', NULL, 20, true),

  -- Site Work / Utility Installers
  ('SK_SITE_WORK_UTILITY_INSTALLERS_TRENCHING_FOR_UTILITIES', 'CAT_SITE_WORK', 'SITE_WORK_UTILITY_INSTALLERS_TRENCHING_FOR_UTILITIES', 'Trenching for utilities', 'Utility Installers', NULL, 10, true),
  ('SK_SITE_WORK_UTILITY_INSTALLERS_INSTALLING_UNDERGROUND_LINES', 'CAT_SITE_WORK', 'SITE_WORK_UTILITY_INSTALLERS_INSTALLING_UNDERGROUND_LINES', 'Installing underground lines (water/sewer/gas/electrical)', 'Utility Installers', NULL, 20, true),
  ('SK_SITE_WORK_UTILITY_INSTALLERS_BACKFILLING_COMPACTION', 'CAT_SITE_WORK', 'SITE_WORK_UTILITY_INSTALLERS_BACKFILLING_COMPACTION', 'Backfilling and compaction', 'Utility Installers', NULL, 30, true),

  -- Site Work / Erosion Control Specialists
  ('SK_SITE_WORK_EROSION_CONTROL_INSTALL_SEDIMENT_BARRIERS', 'CAT_SITE_WORK', 'SITE_WORK_EROSION_CONTROL_INSTALL_SEDIMENT_BARRIERS', 'Installing sediment barriers (silt fences)', 'Erosion Control Specialists', NULL, 10, true),
  ('SK_SITE_WORK_EROSION_CONTROL_STORMWATER_SYSTEM_SETUP', 'CAT_SITE_WORK', 'SITE_WORK_EROSION_CONTROL_STORMWATER_SYSTEM_SETUP', 'Stormwater management system setup', 'Erosion Control Specialists', NULL, 20, true),

  -- Foundation / Concrete Contractors
  ('SK_FOUNDATION_CONCRETE_CONTRACTORS_POUR_FOOTINGS_SLABS', 'CAT_FOUNDATION', 'FOUNDATION_CONCRETE_CONTRACTORS_POUR_FOOTINGS_SLABS', 'Pouring footings and slabs', 'Concrete Contractors', NULL, 10, true),
  ('SK_FOUNDATION_CONCRETE_CONTRACTORS_FINISH_CONCRETE_SURFACES', 'CAT_FOUNDATION', 'FOUNDATION_CONCRETE_CONTRACTORS_FINISH_CONCRETE_SURFACES', 'Finishing concrete surfaces', 'Concrete Contractors', NULL, 20, true),

  -- Foundation / Formwork Carpenters
  ('SK_FOUNDATION_FORMWORK_CARPENTERS_BUILD_ASSEMBLE_FORMS', 'CAT_FOUNDATION', 'FOUNDATION_FORMWORK_CARPENTERS_BUILD_ASSEMBLE_FORMS', 'Building and assembling forms', 'Formwork Carpenters', NULL, 10, true),
  ('SK_FOUNDATION_FORMWORK_CARPENTERS_FORM_REMOVAL_CLEANUP', 'CAT_FOUNDATION', 'FOUNDATION_FORMWORK_CARPENTERS_FORM_REMOVAL_CLEANUP', 'Form removal and cleanup', 'Formwork Carpenters', NULL, 20, true),

  -- Foundation / Rebar Installers
  ('SK_FOUNDATION_REBAR_INSTALLERS_CUT_BEND_REBAR', 'CAT_FOUNDATION', 'FOUNDATION_REBAR_INSTALLERS_CUT_BEND_REBAR', 'Cutting and bending rebar', 'Rebar Installers', NULL, 10, true),
  ('SK_FOUNDATION_REBAR_INSTALLERS_PLACE_TIE_REBAR', 'CAT_FOUNDATION', 'FOUNDATION_REBAR_INSTALLERS_PLACE_TIE_REBAR', 'Placing and tying rebar', 'Rebar Installers', NULL, 20, true),

  -- Foundation / Waterproofing Applicators
  ('SK_FOUNDATION_WATERPROOFING_APPLICATORS_APPLY_SEALANTS_MEMBRANES', 'CAT_FOUNDATION', 'FOUNDATION_WATERPROOFING_APPLICATORS_APPLY_SEALANTS_MEMBRANES', 'Applying sealants and membranes', 'Waterproofing Applicators', NULL, 10, true),
  ('SK_FOUNDATION_WATERPROOFING_APPLICATORS_TEST_FOR_LEAKS', 'CAT_FOUNDATION', 'FOUNDATION_WATERPROOFING_APPLICATORS_TEST_FOR_LEAKS', 'Testing for leaks', 'Waterproofing Applicators', NULL, 20, true),

  -- Structural / Framing / Framers
  ('SK_STRUCTURAL_FRAMING_FRAMERS_WOOD_FRAMING_ASSEMBLY', 'CAT_STRUCTURAL_FRAMING', 'STRUCTURAL_FRAMING_FRAMERS_WOOD_FRAMING_ASSEMBLY', 'Wood framing assembly (walls/floors/roofs)', 'Framers', NULL, 10, true),
  ('SK_STRUCTURAL_FRAMING_FRAMERS_STEEL_CONCRETE_FRAMING_MID_RISE', 'CAT_STRUCTURAL_FRAMING', 'STRUCTURAL_FRAMING_FRAMERS_STEEL_CONCRETE_FRAMING_MID_RISE', 'Steel or concrete framing (for mid-rise)', 'Framers', NULL, 20, true),

  -- Structural / Framing / Carpenters
  ('SK_STRUCTURAL_FRAMING_CARPENTERS_STRUCTURAL_JOINERY_BRACING', 'CAT_STRUCTURAL_FRAMING', 'STRUCTURAL_FRAMING_CARPENTERS_STRUCTURAL_JOINERY_BRACING', 'Structural joinery and bracing', 'Carpenters', NULL, 10, true),
  ('SK_STRUCTURAL_FRAMING_CARPENTERS_SHEATHING_INSTALLATION', 'CAT_STRUCTURAL_FRAMING', 'STRUCTURAL_FRAMING_CARPENTERS_SHEATHING_INSTALLATION', 'Sheathing installation', 'Carpenters', NULL, 20, true),

  -- Structural / Framing / Steel Erectors
  ('SK_STRUCTURAL_FRAMING_STEEL_ERECTORS_WELD_BOLT_STEEL_BEAMS', 'CAT_STRUCTURAL_FRAMING', 'STRUCTURAL_FRAMING_STEEL_ERECTORS_WELD_BOLT_STEEL_BEAMS', 'Welding and bolting steel beams', 'Steel Erectors', NULL, 10, true),
  ('SK_STRUCTURAL_FRAMING_STEEL_ERECTORS_RIGGING_LIFTING_MATERIALS', 'CAT_STRUCTURAL_FRAMING', 'STRUCTURAL_FRAMING_STEEL_ERECTORS_RIGGING_LIFTING_MATERIALS', 'Rigging and lifting materials', 'Steel Erectors', NULL, 20, true),

  -- Structural / Framing / Masonry Contractors
  ('SK_STRUCTURAL_FRAMING_MASONRY_CONTRACTORS_LAY_BLOCKS_BRICKS', 'CAT_STRUCTURAL_FRAMING', 'STRUCTURAL_FRAMING_MASONRY_CONTRACTORS_LAY_BLOCKS_BRICKS', 'Laying blocks or bricks', 'Masonry Contractors', NULL, 10, true),
  ('SK_STRUCTURAL_FRAMING_MASONRY_CONTRACTORS_MORTAR_MIX_APPLICATION', 'CAT_STRUCTURAL_FRAMING', 'STRUCTURAL_FRAMING_MASONRY_CONTRACTORS_MORTAR_MIX_APPLICATION', 'Mortar mixing and application', 'Masonry Contractors', NULL, 20, true),

  -- Structural / Framing / Crane Operators
  ('SK_STRUCTURAL_FRAMING_CRANE_OPERATORS_OPERATE_CONTROLS', 'CAT_STRUCTURAL_FRAMING', 'STRUCTURAL_FRAMING_CRANE_OPERATORS_OPERATE_CONTROLS', 'Operating crane controls', 'Crane Operators', NULL, 10, true),
  ('SK_STRUCTURAL_FRAMING_CRANE_OPERATORS_LOAD_CALC_SAFETY_CHECKS', 'CAT_STRUCTURAL_FRAMING', 'STRUCTURAL_FRAMING_CRANE_OPERATORS_LOAD_CALC_SAFETY_CHECKS', 'Load calculation and safety checks', 'Crane Operators', NULL, 20, true),

  -- Roofing / Roofers
  ('SK_ROOFING_ROOFERS_INSTALL_SHINGLES_TILES_METAL', 'CAT_ROOFING_NEW', 'ROOFING_ROOFERS_INSTALL_SHINGLES_TILES_METAL', 'Installing shingles/tiles/metal roofing', 'Roofers', NULL, 10, true),
  ('SK_ROOFING_ROOFERS_UNDERLAYMENT_APPLICATION', 'CAT_ROOFING_NEW', 'ROOFING_ROOFERS_UNDERLAYMENT_APPLICATION', 'Underlayment application', 'Roofers', NULL, 20, true),

  -- Roofing / Flashing and Waterproofing Specialists
  ('SK_ROOFING_FLASHING_WATERPROOFING_INSTALL_FLASHING', 'CAT_ROOFING_NEW', 'ROOFING_FLASHING_WATERPROOFING_INSTALL_FLASHING', 'Installing roof flashing', 'Flashing and Waterproofing Specialists', NULL, 10, true),
  ('SK_ROOFING_FLASHING_WATERPROOFING_APPLY_MEMBRANES_SEALS', 'CAT_ROOFING_NEW', 'ROOFING_FLASHING_WATERPROOFING_APPLY_MEMBRANES_SEALS', 'Applying membranes and seals', 'Flashing and Waterproofing Specialists', NULL, 20, true),

  -- Roofing / Gutter and Downspout Installers
  ('SK_ROOFING_GUTTER_DOWNSPOUT_GUTTER_FABRICATION_HANGING', 'CAT_ROOFING_NEW', 'ROOFING_GUTTER_DOWNSPOUT_GUTTER_FABRICATION_HANGING', 'Gutter fabrication and hanging', 'Gutter and Downspout Installers', NULL, 10, true),
  ('SK_ROOFING_GUTTER_DOWNSPOUT_DOWNSPOUT_ROUTING_CONNECTION', 'CAT_ROOFING_NEW', 'ROOFING_GUTTER_DOWNSPOUT_DOWNSPOUT_ROUTING_CONNECTION', 'Downspout routing and connection', 'Gutter and Downspout Installers', NULL, 20, true),

  -- Exterior Envelope / Finishes / Siding Installers
  ('SK_EXTERIOR_ENVELOPE_SIDING_CUT_FIT_MATERIALS', 'CAT_EXTERIOR_ENVELOPE_FINISHES', 'EXTERIOR_ENVELOPE_SIDING_CUT_FIT_MATERIALS', 'Cutting and fitting siding materials', 'Siding Installers', NULL, 10, true),
  ('SK_EXTERIOR_ENVELOPE_SIDING_SECURE_TO_STRUCTURE', 'CAT_EXTERIOR_ENVELOPE_FINISHES', 'EXTERIOR_ENVELOPE_SIDING_SECURE_TO_STRUCTURE', 'Securing siding to structure', 'Siding Installers', NULL, 20, true),

  -- Exterior Envelope / Finishes / Bricklayers or Stucco Applicators
  ('SK_EXTERIOR_ENVELOPE_BRICK_STUCCO_BRICKLAYING_PATTERNS', 'CAT_EXTERIOR_ENVELOPE_FINISHES', 'EXTERIOR_ENVELOPE_BRICK_STUCCO_BRICKLAYING_PATTERNS', 'Bricklaying patterns', 'Bricklayers or Stucco Applicators', NULL, 10, true),
  ('SK_EXTERIOR_ENVELOPE_BRICK_STUCCO_STUCCO_MIX_LAYER', 'CAT_EXTERIOR_ENVELOPE_FINISHES', 'EXTERIOR_ENVELOPE_BRICK_STUCCO_STUCCO_MIX_LAYER', 'Stucco mixing and layering', 'Bricklayers or Stucco Applicators', NULL, 20, true),

  -- Exterior Envelope / Finishes / Exterior Painters or Finishers
  ('SK_EXTERIOR_ENVELOPE_EXTERIOR_PAINTERS_SURFACE_PREP', 'CAT_EXTERIOR_ENVELOPE_FINISHES', 'EXTERIOR_ENVELOPE_EXTERIOR_PAINTERS_SURFACE_PREP', 'Surface preparation (sanding/cleaning)', 'Exterior Painters or Finishers', NULL, 10, true),
  ('SK_EXTERIOR_ENVELOPE_EXTERIOR_PAINTERS_APPLY_PAINT_STAINS', 'CAT_EXTERIOR_ENVELOPE_FINISHES', 'EXTERIOR_ENVELOPE_EXTERIOR_PAINTERS_APPLY_PAINT_STAINS', 'Applying paint or stains', 'Exterior Painters or Finishers', NULL, 20, true),

  -- Exterior Envelope / Finishes / Insulation Installers
  ('SK_EXTERIOR_ENVELOPE_INSULATION_CUT_FIT_INSULATION', 'CAT_EXTERIOR_ENVELOPE_FINISHES', 'EXTERIOR_ENVELOPE_INSULATION_CUT_FIT_INSULATION', 'Cutting and fitting insulation', 'Insulation Installers', NULL, 10, true),
  ('SK_EXTERIOR_ENVELOPE_INSULATION_SEAL_GAPS_VAPOR_BARRIERS', 'CAT_EXTERIOR_ENVELOPE_FINISHES', 'EXTERIOR_ENVELOPE_INSULATION_SEAL_GAPS_VAPOR_BARRIERS', 'Sealing gaps and vapor barriers', 'Insulation Installers', NULL, 20, true),

  -- Exterior Envelope / Finishes / Window and Door Flashers
  ('SK_EXTERIOR_ENVELOPE_FLASHERS_INSTALL_FLASHING_AROUND_OPENINGS', 'CAT_EXTERIOR_ENVELOPE_FINISHES', 'EXTERIOR_ENVELOPE_FLASHERS_INSTALL_FLASHING_AROUND_OPENINGS', 'Installing flashing around openings', 'Window and Door Flashers', NULL, 10, true),
  ('SK_EXTERIOR_ENVELOPE_FLASHERS_WEATHERPROOF_TESTING', 'CAT_EXTERIOR_ENVELOPE_FINISHES', 'EXTERIOR_ENVELOPE_FLASHERS_WEATHERPROOF_TESTING', 'Weatherproofing testing', 'Window and Door Flashers', NULL, 20, true),

  -- Doors and Windows / Door Installers
  ('SK_DOORS_WINDOWS_DOOR_INSTALLERS_FRAME_HANG_DOORS', 'CAT_DOORS_WINDOWS', 'DOORS_WINDOWS_DOOR_INSTALLERS_FRAME_HANG_DOORS', 'Framing and hanging doors', 'Door Installers', NULL, 10, true),
  ('SK_DOORS_WINDOWS_DOOR_INSTALLERS_INSTALL_GARAGE_DOORS', 'CAT_DOORS_WINDOWS', 'DOORS_WINDOWS_DOOR_INSTALLERS_INSTALL_GARAGE_DOORS', 'Installing garage doors', 'Door Installers', NULL, 20, true),

  -- Doors and Windows / Window Installers
  ('SK_DOORS_WINDOWS_WINDOW_INSTALLERS_WINDOW_FRAMING_INSERTION', 'CAT_DOORS_WINDOWS', 'DOORS_WINDOWS_WINDOW_INSTALLERS_WINDOW_FRAMING_INSERTION', 'Window framing and insertion', 'Window Installers', NULL, 10, true),
  ('SK_DOORS_WINDOWS_WINDOW_INSTALLERS_GLAZING_SEALING', 'CAT_DOORS_WINDOWS', 'DOORS_WINDOWS_WINDOW_INSTALLERS_GLAZING_SEALING', 'Glazing and sealing', 'Window Installers', NULL, 20, true),

  -- Doors and Windows / Glaziers
  ('SK_DOORS_WINDOWS_GLAZIERS_GLASS_CUTTING_SHAPING', 'CAT_DOORS_WINDOWS', 'DOORS_WINDOWS_GLAZIERS_GLASS_CUTTING_SHAPING', 'Glass cutting and shaping', 'Glaziers', NULL, 10, true),
  ('SK_DOORS_WINDOWS_GLAZIERS_GLASS_INSTALLATION_IN_FRAMES', 'CAT_DOORS_WINDOWS', 'DOORS_WINDOWS_GLAZIERS_GLASS_INSTALLATION_IN_FRAMES', 'Glass installation in frames', 'Glaziers', NULL, 20, true),

  -- Doors and Windows / Hardware Specialists
  ('SK_DOORS_WINDOWS_HARDWARE_SPECIALISTS_INSTALL_LOCKS_HINGES', 'CAT_DOORS_WINDOWS', 'DOORS_WINDOWS_HARDWARE_SPECIALISTS_INSTALL_LOCKS_HINGES', 'Installing locks and hinges', 'Hardware Specialists', NULL, 10, true),
  ('SK_DOORS_WINDOWS_HARDWARE_SPECIALISTS_AUTOMATED_SYSTEMS', 'CAT_DOORS_WINDOWS', 'DOORS_WINDOWS_HARDWARE_SPECIALISTS_AUTOMATED_SYSTEMS', 'Setting up automated systems', 'Hardware Specialists', NULL, 20, true),

  -- Mechanical (HVAC) / HVAC Technicians
  ('SK_MECH_HVAC_HVAC_TECHNICIANS_SYSTEM_DESIGN_SIZING', 'CAT_MECHANICAL_HVAC', 'MECH_HVAC_HVAC_TECHNICIANS_SYSTEM_DESIGN_SIZING', 'System design and sizing', 'HVAC Technicians', NULL, 10, true),
  ('SK_MECH_HVAC_HVAC_TECHNICIANS_UNIT_INSTALLATION', 'CAT_MECHANICAL_HVAC', 'MECH_HVAC_HVAC_TECHNICIANS_UNIT_INSTALLATION', 'Unit installation (furnaces/AC)', 'HVAC Technicians', NULL, 20, true),

  -- Mechanical (HVAC) / Ductwork Fabricators and Installers
  ('SK_MECH_HVAC_DUCTWORK_FABRICATORS_DUCT_FABRICATION', 'CAT_MECHANICAL_HVAC', 'MECH_HVAC_DUCTWORK_FABRICATORS_DUCT_FABRICATION', 'Duct fabrication (cutting/bending)', 'Ductwork Fabricators and Installers', NULL, 10, true),
  ('SK_MECH_HVAC_DUCTWORK_FABRICATORS_DUCT_SEALING_INSULATION', 'CAT_MECHANICAL_HVAC', 'MECH_HVAC_DUCTWORK_FABRICATORS_DUCT_SEALING_INSULATION', 'Duct sealing and insulation', 'Ductwork Fabricators and Installers', NULL, 20, true),

  -- Mechanical (HVAC) / Boiler or Furnace Installers
  ('SK_MECH_HVAC_BOILER_FURNACE_INSTALLERS_BOILER_ASSEMBLY_CONNECTION', 'CAT_MECHANICAL_HVAC', 'MECH_HVAC_BOILER_FURNACE_INSTALLERS_BOILER_ASSEMBLY_CONNECTION', 'Boiler assembly and connection', 'Boiler or Furnace Installers', NULL, 10, true),
  ('SK_MECH_HVAC_BOILER_FURNACE_INSTALLERS_FURNACE_VENTING', 'CAT_MECHANICAL_HVAC', 'MECH_HVAC_BOILER_FURNACE_INSTALLERS_FURNACE_VENTING', 'Furnace venting', 'Boiler or Furnace Installers', NULL, 20, true),

  -- Mechanical (HVAC) / Ventilation Specialists
  ('SK_MECH_HVAC_VENTILATION_SPECIALISTS_EXHAUST_INSTALL', 'CAT_MECHANICAL_HVAC', 'MECH_HVAC_VENTILATION_SPECIALISTS_EXHAUST_INSTALL', 'Exhaust system installation', 'Ventilation Specialists', NULL, 10, true),
  ('SK_MECH_HVAC_VENTILATION_SPECIALISTS_FRESH_AIR_INTAKE', 'CAT_MECHANICAL_HVAC', 'MECH_HVAC_VENTILATION_SPECIALISTS_FRESH_AIR_INTAKE', 'Fresh air intake setup', 'Ventilation Specialists', NULL, 20, true),

  -- Electrical / Electricians
  ('SK_ELECTRICAL_ELECTRICIANS_WIRING_INSTALLATION_ROUGH_IN', 'CAT_ELECTRICAL_NEW', 'ELECTRICAL_ELECTRICIANS_WIRING_INSTALLATION_ROUGH_IN', 'Wiring installation (rough-in)', 'Electricians', NULL, 10, true),
  ('SK_ELECTRICAL_ELECTRICIANS_PANEL_BREAKER_SETUP', 'CAT_ELECTRICAL_NEW', 'ELECTRICAL_ELECTRICIANS_PANEL_BREAKER_SETUP', 'Panel and breaker setup', 'Electricians', NULL, 20, true),

  -- Electrical / Low-Voltage Technicians
  ('SK_ELECTRICAL_LOW_VOLTAGE_DATA_CABLING_ETHERNET', 'CAT_ELECTRICAL_NEW', 'ELECTRICAL_LOW_VOLTAGE_DATA_CABLING_ETHERNET', 'Data cabling (Ethernet)', 'Low-Voltage Technicians', NULL, 10, true),
  ('SK_ELECTRICAL_LOW_VOLTAGE_SECURITY_SMART_HOME', 'CAT_ELECTRICAL_NEW', 'ELECTRICAL_LOW_VOLTAGE_SECURITY_SMART_HOME', 'Security/smart home integration', 'Low-Voltage Technicians', NULL, 20, true),

  -- Electrical / Lighting Installers
  ('SK_ELECTRICAL_LIGHTING_INSTALLERS_FIXTURE_MOUNTING', 'CAT_ELECTRICAL_NEW', 'ELECTRICAL_LIGHTING_INSTALLERS_FIXTURE_MOUNTING', 'Fixture mounting', 'Lighting Installers', NULL, 10, true),
  ('SK_ELECTRICAL_LIGHTING_INSTALLERS_WIRING_DIMMER_SETUP', 'CAT_ELECTRICAL_NEW', 'ELECTRICAL_LIGHTING_INSTALLERS_WIRING_DIMMER_SETUP', 'Wiring and dimmer setup', 'Lighting Installers', NULL, 20, true),

  -- Electrical / Generator or Solar Installers
  ('SK_ELECTRICAL_GENERATOR_SOLAR_INSTALLERS_GENERATOR_HOOKUP', 'CAT_ELECTRICAL_NEW', 'ELECTRICAL_GENERATOR_SOLAR_INSTALLERS_GENERATOR_HOOKUP', 'Generator hookup', 'Generator or Solar Installers', NULL, 10, true),
  ('SK_ELECTRICAL_GENERATOR_SOLAR_INSTALLERS_SOLAR_PANEL_MOUNT_WIRING', 'CAT_ELECTRICAL_NEW', 'ELECTRICAL_GENERATOR_SOLAR_INSTALLERS_SOLAR_PANEL_MOUNT_WIRING', 'Solar panel mounting and wiring', 'Generator or Solar Installers', NULL, 20, true),

  -- Plumbing / Plumbers
  ('SK_PLUMBING_PLUMBERS_PIPE_INSTALLATION_ROUGH_IN', 'CAT_PLUMBING_NEW', 'PLUMBING_PLUMBERS_PIPE_INSTALLATION_ROUGH_IN', 'Pipe installation (rough-in)', 'Plumbers', NULL, 10, true),
  ('SK_PLUMBING_PLUMBERS_FIXTURE_CONNECTION_SINKS_TOILETS', 'CAT_PLUMBING_NEW', 'PLUMBING_PLUMBERS_FIXTURE_CONNECTION_SINKS_TOILETS', 'Fixture connection (sinks/toilets)', 'Plumbers', NULL, 20, true),

  -- Plumbing / Pipefitters
  ('SK_PLUMBING_PIPEFITTERS_GAS_LINE_INSTALLATION', 'CAT_PLUMBING_NEW', 'PLUMBING_PIPEFITTERS_GAS_LINE_INSTALLATION', 'Gas line installation', 'Pipefitters', NULL, 10, true),
  ('SK_PLUMBING_PIPEFITTERS_WATER_LINE_PRESSURE_TEST', 'CAT_PLUMBING_NEW', 'PLUMBING_PIPEFITTERS_WATER_LINE_PRESSURE_TEST', 'Water line pressure testing', 'Pipefitters', NULL, 20, true),

  -- Plumbing / Septic or Sewer Specialists
  ('SK_PLUMBING_SEPTIC_SEWER_SPECIALISTS_SEPTIC_TANK_INSTALLATION', 'CAT_PLUMBING_NEW', 'PLUMBING_SEPTIC_SEWER_SPECIALISTS_SEPTIC_TANK_INSTALLATION', 'Septic tank installation', 'Septic or Sewer Specialists', NULL, 10, true),
  ('SK_PLUMBING_SEPTIC_SEWER_SPECIALISTS_SEWER_LINE_TRENCH_CONNECTION', 'CAT_PLUMBING_NEW', 'PLUMBING_SEPTIC_SEWER_SPECIALISTS_SEWER_LINE_TRENCH_CONNECTION', 'Sewer line trenching and connection', 'Septic or Sewer Specialists', NULL, 20, true),

  -- Plumbing / Fixture Installers
  ('SK_PLUMBING_FIXTURE_INSTALLERS_INSTALL_SHOWERS_BATHTUBS', 'CAT_PLUMBING_NEW', 'PLUMBING_FIXTURE_INSTALLERS_INSTALL_SHOWERS_BATHTUBS', 'Installing showers/bathtubs', 'Fixture Installers', NULL, 10, true),
  ('SK_PLUMBING_FIXTURE_INSTALLERS_LEAK_TEST_FIXTURES', 'CAT_PLUMBING_NEW', 'PLUMBING_FIXTURE_INSTALLERS_LEAK_TEST_FIXTURES', 'Leak testing fixtures', 'Fixture Installers', NULL, 20, true),

  -- Insulation and Moisture Protection / Insulation Contractors
  ('SK_INSULATION_INSULATION_CONTRACTORS_WALL_ATTIC_BLOWING', 'CAT_INSULATION_MOISTURE', 'INSULATION_INSULATION_CONTRACTORS_WALL_ATTIC_BLOWING', 'Wall/attic insulation blowing', 'Insulation Contractors', NULL, 10, true),
  ('SK_INSULATION_INSULATION_CONTRACTORS_FLOOR_INSULATION_FITTING', 'CAT_INSULATION_MOISTURE', 'INSULATION_INSULATION_CONTRACTORS_FLOOR_INSULATION_FITTING', 'Floor insulation fitting', 'Insulation Contractors', NULL, 20, true),

  -- Insulation and Moisture Protection / Vapor Barrier Installers
  ('SK_INSULATION_VAPOR_BARRIER_INSTALLERS_BARRIER_SHEET_INSTALL', 'CAT_INSULATION_MOISTURE', 'INSULATION_VAPOR_BARRIER_INSTALLERS_BARRIER_SHEET_INSTALL', 'Barrier sheet installation', 'Vapor Barrier Installers', NULL, 10, true),
  ('SK_INSULATION_VAPOR_BARRIER_INSTALLERS_SEALING_JOINTS', 'CAT_INSULATION_MOISTURE', 'INSULATION_VAPOR_BARRIER_INSTALLERS_SEALING_JOINTS', 'Sealing joints', 'Vapor Barrier Installers', NULL, 20, true),

  -- Insulation and Moisture Protection / Soundproofing Specialists
  ('SK_INSULATION_SOUNDPROOFING_SPECIALISTS_ACOUSTIC_MATERIAL_APPLICATION', 'CAT_INSULATION_MOISTURE', 'INSULATION_SOUNDPROOFING_SPECIALISTS_ACOUSTIC_MATERIAL_APPLICATION', 'Acoustic material application', 'Soundproofing Specialists', NULL, 10, true),
  ('SK_INSULATION_SOUNDPROOFING_SPECIALISTS_TEST_SOUND_LEVELS', 'CAT_INSULATION_MOISTURE', 'INSULATION_SOUNDPROOFING_SPECIALISTS_TEST_SOUND_LEVELS', 'Testing sound levels', 'Soundproofing Specialists', NULL, 20, true),

  -- Drywall / Drywall Hangers
  ('SK_DRYWALL_DRYWALL_HANGERS_MEASURE_CUT_BOARDS', 'CAT_DRYWALL_NEW', 'DRYWALL_DRYWALL_HANGERS_MEASURE_CUT_BOARDS', 'Measuring and cutting boards', 'Drywall Hangers', NULL, 10, true),
  ('SK_DRYWALL_DRYWALL_HANGERS_HANG_SECURE_BOARDS', 'CAT_DRYWALL_NEW', 'DRYWALL_DRYWALL_HANGERS_HANG_SECURE_BOARDS', 'Hanging and securing boards', 'Drywall Hangers', NULL, 20, true),

  -- Drywall / Tapers and Finishers
  ('SK_DRYWALL_TAPERS_FINISHERS_APPLY_JOINT_COMPOUND', 'CAT_DRYWALL_NEW', 'DRYWALL_TAPERS_FINISHERS_APPLY_JOINT_COMPOUND', 'Applying joint compound', 'Tapers and Finishers', NULL, 10, true),
  ('SK_DRYWALL_TAPERS_FINISHERS_SAND_SMOOTH', 'CAT_DRYWALL_NEW', 'DRYWALL_TAPERS_FINISHERS_SAND_SMOOTH', 'Sanding and smoothing', 'Tapers and Finishers', NULL, 20, true),

  -- Drywall / Texturing Specialists
  ('SK_DRYWALL_TEXTURING_SPECIALISTS_KNOCKDOWN_TEXTURE', 'CAT_DRYWALL_NEW', 'DRYWALL_TEXTURING_SPECIALISTS_KNOCKDOWN_TEXTURE', 'Applying knockdown texture', 'Texturing Specialists', NULL, 10, true),
  ('SK_DRYWALL_TEXTURING_SPECIALISTS_SMOOTH_FINISH', 'CAT_DRYWALL_NEW', 'DRYWALL_TEXTURING_SPECIALISTS_SMOOTH_FINISH', 'Smooth finish application', 'Texturing Specialists', NULL, 20, true),

  -- Interiors / Finishes / Painters
  ('SK_INTERIORS_PAINTERS_SURFACE_PREP', 'CAT_INTERIORS_FINISHES', 'INTERIORS_PAINTERS_SURFACE_PREP', 'Surface prep (taping/sanding)', 'Painters', NULL, 10, true),
  ('SK_INTERIORS_PAINTERS_APPLY_INTERIOR_PAINT', 'CAT_INTERIORS_FINISHES', 'INTERIORS_PAINTERS_APPLY_INTERIOR_PAINT', 'Applying interior paint', 'Painters', NULL, 20, true),

  -- Interiors / Finishes / Tile Setters
  ('SK_INTERIORS_TILE_SETTERS_TILE_CUTTING_LAYOUT', 'CAT_INTERIORS_FINISHES', 'INTERIORS_TILE_SETTERS_TILE_CUTTING_LAYOUT', 'Tile cutting and layout', 'Tile Setters', NULL, 10, true),
  ('SK_INTERIORS_TILE_SETTERS_GROUTING_SEALING', 'CAT_INTERIORS_FINISHES', 'INTERIORS_TILE_SETTERS_GROUTING_SEALING', 'Grouting and sealing', 'Tile Setters', NULL, 20, true),

  -- Interiors / Finishes / Flooring Installers
  ('SK_INTERIORS_FLOORING_INSTALLERS_SUBFLOOR_PREP', 'CAT_INTERIORS_FINISHES', 'INTERIORS_FLOORING_INSTALLERS_SUBFLOOR_PREP', 'Subfloor preparation', 'Flooring Installers', NULL, 10, true),
  ('SK_INTERIORS_FLOORING_INSTALLERS_INSTALL_HARDWOOD_CARPET_VINYL', 'CAT_INTERIORS_FINISHES', 'INTERIORS_FLOORING_INSTALLERS_INSTALL_HARDWOOD_CARPET_VINYL', 'Installing hardwood/carpet/vinyl', 'Flooring Installers', NULL, 20, true),

  -- Interiors / Finishes / Trim Carpenters
  ('SK_INTERIORS_TRIM_CARPENTERS_CUT_FIT_TRIM', 'CAT_INTERIORS_FINISHES', 'INTERIORS_TRIM_CARPENTERS_CUT_FIT_TRIM', 'Cutting and fitting trim', 'Trim Carpenters', NULL, 10, true),
  ('SK_INTERIORS_TRIM_CARPENTERS_INSTALL_BUILT_INS', 'CAT_INTERIORS_FINISHES', 'INTERIORS_TRIM_CARPENTERS_INSTALL_BUILT_INS', 'Installing built-ins', 'Trim Carpenters', NULL, 20, true),

  -- Interiors / Finishes / Wallpaper Hangers
  ('SK_INTERIORS_WALLPAPER_HANGERS_WALL_PREP', 'CAT_INTERIORS_FINISHES', 'INTERIORS_WALLPAPER_HANGERS_WALL_PREP', 'Wall preparation', 'Wallpaper Hangers', NULL, 10, true),
  ('SK_INTERIORS_WALLPAPER_HANGERS_PATTERN_MATCHING_HANGING', 'CAT_INTERIORS_FINISHES', 'INTERIORS_WALLPAPER_HANGERS_PATTERN_MATCHING_HANGING', 'Pattern matching and hanging', 'Wallpaper Hangers', NULL, 20, true),

  -- Kitchen, Bath, and Cabinetry / Cabinet Makers and Installers
  ('SK_KITCHEN_BATH_CABINETRY_CABINET_MAKERS_ASSEMBLY', 'CAT_KITCHEN_BATH_CABINETRY', 'KITCHEN_BATH_CABINETRY_CABINET_MAKERS_ASSEMBLY', 'Cabinet assembly', 'Cabinet Makers and Installers', NULL, 10, true),
  ('SK_KITCHEN_BATH_CABINETRY_CABINET_MAKERS_LEVEL_SECURE', 'CAT_KITCHEN_BATH_CABINETRY', 'KITCHEN_BATH_CABINETRY_CABINET_MAKERS_LEVEL_SECURE', 'Leveling and securing cabinets', 'Cabinet Makers and Installers', NULL, 20, true),

  -- Kitchen, Bath, and Cabinetry / Countertop Fabricators
  ('SK_KITCHEN_BATH_CABINETRY_COUNTERTOP_FABRICATORS_MEASURE_CUT', 'CAT_KITCHEN_BATH_CABINETRY', 'KITCHEN_BATH_CABINETRY_COUNTERTOP_FABRICATORS_MEASURE_CUT', 'Measuring and cutting countertops', 'Countertop Fabricators', NULL, 10, true),
  ('SK_KITCHEN_BATH_CABINETRY_COUNTERTOP_FABRICATORS_POLISH_EDGE', 'CAT_KITCHEN_BATH_CABINETRY', 'KITCHEN_BATH_CABINETRY_COUNTERTOP_FABRICATORS_POLISH_EDGE', 'Polishing and edging', 'Countertop Fabricators', NULL, 20, true),

  -- Kitchen, Bath, and Cabinetry / Appliance Installers
  ('SK_KITCHEN_BATH_CABINETRY_APPLIANCE_INSTALLERS_ELECTRICAL_GAS_HOOKUP', 'CAT_KITCHEN_BATH_CABINETRY', 'KITCHEN_BATH_CABINETRY_APPLIANCE_INSTALLERS_ELECTRICAL_GAS_HOOKUP', 'Electrical/gas hookup', 'Appliance Installers', NULL, 10, true),
  ('SK_KITCHEN_BATH_CABINETRY_APPLIANCE_INSTALLERS_LEVEL_TEST', 'CAT_KITCHEN_BATH_CABINETRY', 'KITCHEN_BATH_CABINETRY_APPLIANCE_INSTALLERS_LEVEL_TEST', 'Leveling and testing', 'Appliance Installers', NULL, 20, true),

  -- Kitchen, Bath, and Cabinetry / Millwork Specialists
  ('SK_KITCHEN_BATH_CABINETRY_MILLWORK_SPECIALISTS_CUSTOM_WOOD_CUTTING', 'CAT_KITCHEN_BATH_CABINETRY', 'KITCHEN_BATH_CABINETRY_MILLWORK_SPECIALISTS_CUSTOM_WOOD_CUTTING', 'Custom wood cutting', 'Millwork Specialists', NULL, 10, true),
  ('SK_KITCHEN_BATH_CABINETRY_MILLWORK_SPECIALISTS_FINISHING_STAINING', 'CAT_KITCHEN_BATH_CABINETRY', 'KITCHEN_BATH_CABINETRY_MILLWORK_SPECIALISTS_FINISHING_STAINING', 'Finishing and staining', 'Millwork Specialists', NULL, 20, true),

  -- Specialties and Equipment / Elevator Installers
  ('SK_SPECIALTIES_ELEVATOR_INSTALLERS_SHAFT_CONSTRUCTION', 'CAT_SPECIALTIES_EQUIPMENT', 'SPECIALTIES_ELEVATOR_INSTALLERS_SHAFT_CONSTRUCTION', 'Shaft construction', 'Elevator Installers', NULL, 10, true),
  ('SK_SPECIALTIES_ELEVATOR_INSTALLERS_CAB_CONTROL_INSTALLATION', 'CAT_SPECIALTIES_EQUIPMENT', 'SPECIALTIES_ELEVATOR_INSTALLERS_CAB_CONTROL_INSTALLATION', 'Cab and control installation', 'Elevator Installers', NULL, 20, true),

  -- Specialties and Equipment / Fireplace or Stove Installers
  ('SK_SPECIALTIES_FIREPLACE_STOVE_CHIMNEY_VENTING', 'CAT_SPECIALTIES_EQUIPMENT', 'SPECIALTIES_FIREPLACE_STOVE_CHIMNEY_VENTING', 'Chimney venting', 'Fireplace or Stove Installers', NULL, 10, true),
  ('SK_SPECIALTIES_FIREPLACE_STOVE_UNIT_MOUNTING', 'CAT_SPECIALTIES_EQUIPMENT', 'SPECIALTIES_FIREPLACE_STOVE_UNIT_MOUNTING', 'Unit mounting', 'Fireplace or Stove Installers', NULL, 20, true),

  -- Specialties and Equipment / Security System Installers
  ('SK_SPECIALTIES_SECURITY_SYSTEM_INSTALLERS_WIRING_ALARMS_CAMERAS', 'CAT_SPECIALTIES_EQUIPMENT', 'SPECIALTIES_SECURITY_SYSTEM_INSTALLERS_WIRING_ALARMS_CAMERAS', 'Wiring alarms/cameras', 'Security System Installers', NULL, 10, true),
  ('SK_SPECIALTIES_SECURITY_SYSTEM_INSTALLERS_PROGRAM_SYSTEMS', 'CAT_SPECIALTIES_EQUIPMENT', 'SPECIALTIES_SECURITY_SYSTEM_INSTALLERS_PROGRAM_SYSTEMS', 'Programming systems', 'Security System Installers', NULL, 20, true),

  -- Specialties and Equipment / Audio-Visual Technicians
  ('SK_SPECIALTIES_AUDIO_VISUAL_TECHNICIANS_CABLE_ROUTING', 'CAT_SPECIALTIES_EQUIPMENT', 'SPECIALTIES_AUDIO_VISUAL_TECHNICIANS_CABLE_ROUTING', 'Cable routing', 'Audio-Visual Technicians', NULL, 10, true),
  ('SK_SPECIALTIES_AUDIO_VISUAL_TECHNICIANS_SYSTEM_INTEGRATION', 'CAT_SPECIALTIES_EQUIPMENT', 'SPECIALTIES_AUDIO_VISUAL_TECHNICIANS_SYSTEM_INTEGRATION', 'System integration (home theater)', 'Audio-Visual Technicians', NULL, 20, true),

  -- Specialties and Equipment / Furnishing Installers
  ('SK_SPECIALTIES_FURNISHING_INSTALLERS_INSTALL_BLINDS_SHELVES', 'CAT_SPECIALTIES_EQUIPMENT', 'SPECIALTIES_FURNISHING_INSTALLERS_INSTALL_BLINDS_SHELVES', 'Installing blinds/shelves', 'Furnishing Installers', NULL, 10, true),
  ('SK_SPECIALTIES_FURNISHING_INSTALLERS_PARTITION_ASSEMBLY', 'CAT_SPECIALTIES_EQUIPMENT', 'SPECIALTIES_FURNISHING_INSTALLERS_PARTITION_ASSEMBLY', 'Partition assembly', 'Furnishing Installers', NULL, 20, true),

  -- Fire Protection / Sprinkler System Installers
  ('SK_FIRE_PROTECTION_SPRINKLER_PIPE_LAYOUT_INSTALL', 'CAT_FIRE_PROTECTION', 'FIRE_PROTECTION_SPRINKLER_PIPE_LAYOUT_INSTALL', 'Pipe layout and installation', 'Sprinkler System Installers', NULL, 10, true),
  ('SK_FIRE_PROTECTION_SPRINKLER_HEAD_PLACEMENT_TESTING', 'CAT_FIRE_PROTECTION', 'FIRE_PROTECTION_SPRINKLER_HEAD_PLACEMENT_TESTING', 'Head placement and testing', 'Sprinkler System Installers', NULL, 20, true),

  -- Fire Protection / Fire Alarm Technicians
  ('SK_FIRE_PROTECTION_FIRE_ALARM_TECHNICIANS_WIRING_DETECTORS', 'CAT_FIRE_PROTECTION', 'FIRE_PROTECTION_FIRE_ALARM_TECHNICIANS_WIRING_DETECTORS', 'Wiring detectors', 'Fire Alarm Technicians', NULL, 10, true),
  ('SK_FIRE_PROTECTION_FIRE_ALARM_TECHNICIANS_PANEL_PROGRAMMING', 'CAT_FIRE_PROTECTION', 'FIRE_PROTECTION_FIRE_ALARM_TECHNICIANS_PANEL_PROGRAMMING', 'Panel programming', 'Fire Alarm Technicians', NULL, 20, true),

  -- Fire Protection / Smoke Control Specialists
  ('SK_FIRE_PROTECTION_SMOKE_CONTROL_SPECIALISTS_VENTILATION_SETUP', 'CAT_FIRE_PROTECTION', 'FIRE_PROTECTION_SMOKE_CONTROL_SPECIALISTS_VENTILATION_SETUP', 'Ventilation system setup', 'Smoke Control Specialists', NULL, 10, true),
  ('SK_FIRE_PROTECTION_SMOKE_CONTROL_SPECIALISTS_TEST_AIRFLOW', 'CAT_FIRE_PROTECTION', 'FIRE_PROTECTION_SMOKE_CONTROL_SPECIALISTS_TEST_AIRFLOW', 'Testing airflow', 'Smoke Control Specialists', NULL, 20, true),

  -- Landscaping and Exterior Improvements / Landscapers
  ('SK_LANDSCAPING_LANDSCAPERS_PLANTING_SOD', 'CAT_LANDSCAPING_EXTERIOR', 'LANDSCAPING_LANDSCAPERS_PLANTING_SOD', 'Planting and sod laying', 'Landscapers', NULL, 10, true),
  ('SK_LANDSCAPING_LANDSCAPERS_IRRIGATION_INSTALLATION', 'CAT_LANDSCAPING_EXTERIOR', 'LANDSCAPING_LANDSCAPERS_IRRIGATION_INSTALLATION', 'Irrigation system installation', 'Landscapers', NULL, 20, true),

  -- Landscaping and Exterior Improvements / Paving Contractors
  ('SK_LANDSCAPING_PAVING_CONTRACTORS_BASE_PREP', 'CAT_LANDSCAPING_EXTERIOR', 'LANDSCAPING_PAVING_CONTRACTORS_BASE_PREP', 'Base preparation', 'Paving Contractors', NULL, 10, true),
  ('SK_LANDSCAPING_PAVING_CONTRACTORS_PAVING_ASPHALT_CONCRETE', 'CAT_LANDSCAPING_EXTERIOR', 'LANDSCAPING_PAVING_CONTRACTORS_PAVING_ASPHALT_CONCRETE', 'Paving (asphalt/concrete)', 'Paving Contractors', NULL, 20, true),

  -- Landscaping and Exterior Improvements / Fencing and Gate Installers
  ('SK_LANDSCAPING_FENCING_GATE_INSTALLERS_POST_SETTING', 'CAT_LANDSCAPING_EXTERIOR', 'LANDSCAPING_FENCING_GATE_INSTALLERS_POST_SETTING', 'Post setting', 'Fencing and Gate Installers', NULL, 10, true),
  ('SK_LANDSCAPING_FENCING_GATE_INSTALLERS_GATE_AUTOMATION', 'CAT_LANDSCAPING_EXTERIOR', 'LANDSCAPING_FENCING_GATE_INSTALLERS_GATE_AUTOMATION', 'Gate automation', 'Fencing and Gate Installers', NULL, 20, true),

  -- Landscaping and Exterior Improvements / Deck or Balcony Builders
  ('SK_LANDSCAPING_DECK_BALCONY_BUILDERS_FRAMING_DECKS', 'CAT_LANDSCAPING_EXTERIOR', 'LANDSCAPING_DECK_BALCONY_BUILDERS_FRAMING_DECKS', 'Framing decks', 'Deck or Balcony Builders', NULL, 10, true),
  ('SK_LANDSCAPING_DECK_BALCONY_BUILDERS_RAILING_INSTALLATION', 'CAT_LANDSCAPING_EXTERIOR', 'LANDSCAPING_DECK_BALCONY_BUILDERS_RAILING_INSTALLATION', 'Railing installation', 'Deck or Balcony Builders', NULL, 20, true),

  -- Landscaping and Exterior Improvements / Exterior Lighting and Signage Installers
  ('SK_LANDSCAPING_EXTERIOR_LIGHTING_SIGNAGE_FIXTURE_MOUNTING', 'CAT_LANDSCAPING_EXTERIOR', 'LANDSCAPING_EXTERIOR_LIGHTING_SIGNAGE_FIXTURE_MOUNTING', 'Fixture mounting', 'Exterior Lighting and Signage Installers', NULL, 10, true),
  ('SK_LANDSCAPING_EXTERIOR_LIGHTING_SIGNAGE_WIRING_TIMERS', 'CAT_LANDSCAPING_EXTERIOR', 'LANDSCAPING_EXTERIOR_LIGHTING_SIGNAGE_WIRING_TIMERS', 'Wiring and timers', 'Exterior Lighting and Signage Installers', NULL, 20, true)
ON CONFLICT ("code") DO UPDATE
SET
  "categoryId" = EXCLUDED."categoryId",
  "label" = EXCLUDED."label",
  "tradeLabel" = EXCLUDED."tradeLabel",
  "sortOrder" = EXCLUDED."sortOrder",
  "active" = true;
